# Data Analysis with Python - Task 2

### Task 2 : Data Manipulation with Pandas 

##  Description:
#### This task involves using the Pandas library to manipulate data.
## Objective : 
#### Load a CSV file into a Pandas DataFrame.
#### Perform operations like filtering data based on conditions, handling missing values, and calculating summary statistics.

In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset = pd.read_csv('01.Data Cleaning and Preprocessing.csv')

In [3]:
dataset.head(10) # Gives the first ten rows of the Dataframe

Observation  Y-Kappa  ChipRate  BF-CMratio  BlowFlow  ChipLevel4   \
0    31-00:00    23.10    16.520     121.717  1177.607      169.805   
1    31-01:00    27.60    16.810      79.022  1328.360      341.327   
2    31-02:00    23.19    16.709      79.562  1329.407      239.161   
3    31-03:00    23.60    16.478      81.011  1334.877      213.527   
4    31-04:00    22.90    15.618      93.244  1334.168      243.131   
5     1-08:00    14.23    15.350      85.518  1171.604      198.538   
6     1-09:00    13.49    13.700      98.186  1243.688      116.275   
7    31-06:00    22.65    14.100      91.887  1307.852      288.989   
8    31-07:00    22.50    14.233      97.249  1346.900      330.325   
9    31-08:00    24.70    13.850      96.208  1334.892      362.511   

   T-upperExt-2   T-lowerExt-2    UCZAA  WhiteFlow-4   ...  SteamFlow-4   \
0        358.282         329.545  1.443       599.253  ...        67.122   
1        351.050         329.067  1.549       537.201  ...        60.012   
2        350.022         329.260  1.600       549.611  ...        61.304   
3        350.938         331.142  1.604       623.362  ...        68.496   
4        351.640         332.709    NaN       638.672  ...        70.022   
5        344.014         325.195  1.436       628.245  ...        65.225   
6        346.208         326.982  1.434       696.766  ...        72.989   
7        352.321         331.162  1.468       625.549  ...        71.298   
8        352.687         328.894  1.480       591.827  ...        68.791   
9        352.372         327.358  1.515       553.172  ...        64.249   

   Lower-HeatT-3  Upper-HeatT-3   ChipMass-4   WeakLiquorF   BlackFlow-2   \
0        329.432         303.099      175.964      1127.197      1319.039   
1        330.823         304.879      163.202       665.975      1297.317   
2        329.140         303.383      164.013       677.534      1327.072   
3        328.875         302.254      181.487       767.853      1324.461   
4        328.352         300.954      183.929       888.448      1343.424   
5        322.103         298.517      165.814       826.243       907.641   
6        322.982         296.080      182.018       784.281       929.527   
7        329.662         301.539      179.886       837.178      1315.111   
8        331.485         303.488      174.804       889.516      1317.912   
9        332.264         305.419      166.120       909.810      1318.725   

   WeakWashF   SteamHeatF-3   T-Top-Chips-4   SulphidityL-4   
0     257.325         54.612         252.077             NaN  
1     241.182         46.603         251.406           29.11  
2     237.272         51.795         251.335             NaN  
3     239.478         54.846         250.312           29.02  
4     215.372         54.186         249.916           29.01  
5     595.875         52.807         249.580           30.34  
6     201.272         58.118         248.741             NaN  
7     234.047         53.805         249.971           29.22  
8     226.319         52.546         250.414             NaN  
9     180.375         48.842         251.121           29.21  

[10 rows x 23 columns]

In [4]:
print(dataset.shape)

(324, 23)


In [5]:
# Therefore, the given dataset contains 324 rows and 23 columns

In [6]:
print(dataset.columns)

Index(['Observation', 'Y-Kappa', 'ChipRate', 'BF-CMratio', 'BlowFlow',
       'ChipLevel4 ', 'T-upperExt-2 ', 'T-lowerExt-2  ', 'UCZAA',
       'WhiteFlow-4 ', 'AAWhiteSt-4 ', 'AA-Wood-4  ', 'ChipMoisture-4 ',
       'SteamFlow-4 ', 'Lower-HeatT-3', 'Upper-HeatT-3 ', 'ChipMass-4 ',
       'WeakLiquorF ', 'BlackFlow-2 ', 'WeakWashF ', 'SteamHeatF-3 ',
       'T-Top-Chips-4 ', 'SulphidityL-4 '],
      dtype='object')


In [7]:
print(dataset.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 324 entries, 0 to 323
Data columns (total 23 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Observation      324 non-null    object 
 1   Y-Kappa          324 non-null    float64
 2   ChipRate         319 non-null    float64
 3   BF-CMratio       307 non-null    float64
 4   BlowFlow         308 non-null    float64
 5   ChipLevel4       323 non-null    float64
 6   T-upperExt-2     322 non-null    float64
 7   T-lowerExt-2     322 non-null    float64
 8   UCZAA            299 non-null    float64
 9   WhiteFlow-4      323 non-null    float64
 10  AAWhiteSt-4      173 non-null    float64
 11  AA-Wood-4        323 non-null    float64
 12  ChipMoisture-4   323 non-null    float64
 13  SteamFlow-4      323 non-null    float64
 14  Lower-HeatT-3    322 non-null    float64
 15  Upper-HeatT-3    322 non-null    float64
 16  ChipMass-4       323 non-null    float64
 17  WeakLiquorF     

In [8]:
print(dataset.dtypes)

Observation         object
Y-Kappa            float64
ChipRate           float64
BF-CMratio         float64
BlowFlow           float64
ChipLevel4         float64
T-upperExt-2       float64
T-lowerExt-2       float64
UCZAA              float64
WhiteFlow-4        float64
AAWhiteSt-4        float64
AA-Wood-4          float64
ChipMoisture-4     float64
SteamFlow-4        float64
Lower-HeatT-3      float64
Upper-HeatT-3      float64
ChipMass-4         float64
WeakLiquorF        float64
BlackFlow-2        float64
WeakWashF          float64
SteamHeatF-3       float64
T-Top-Chips-4      float64
SulphidityL-4      float64
dtype: object


##  Missing Values :-

In [9]:
print(dataset.isnull().sum())

Observation          0
Y-Kappa              0
ChipRate             5
BF-CMratio          17
BlowFlow            16
ChipLevel4           1
T-upperExt-2         2
T-lowerExt-2         2
UCZAA               25
WhiteFlow-4          1
AAWhiteSt-4        151
AA-Wood-4            1
ChipMoisture-4       1
SteamFlow-4          1
Lower-HeatT-3        2
Upper-HeatT-3        2
ChipMass-4           1
WeakLiquorF          1
BlackFlow-2          2
WeakWashF            1
SteamHeatF-3         2
T-Top-Chips-4        1
SulphidityL-4      151
dtype: int64


In [10]:
# We can observe that missing values are present for several features in case of the given dataset

#### Handling Missing Values :

In [11]:
print(dataset['ChipRate'].mean())
print(dataset['ChipRate'].median())

14.347937304075236
14.308


In [12]:
dataset['ChipRate'] = dataset['ChipRate'].fillna(dataset['ChipRate'].mean())

In [13]:
print(dataset['BF-CMratio'].mean())
print(dataset['BF-CMratio'].median())

87.46445602605863
86.739


In [14]:
dataset['BF-CMratio'] = dataset['BF-CMratio'].fillna(dataset['BF-CMratio'].mean())

In [15]:
print(dataset['BlowFlow'].mean())
print(dataset['BlowFlow'].median())

1237.8376136363638
1273.1385


In [16]:
dataset['BlowFlow'] = dataset['BlowFlow'].fillna(dataset['BlowFlow'].median())

In [17]:
print(dataset['UCZAA'].mean())
print(dataset['UCZAA'].median())

1.492010033444816
1.498


In [18]:
dataset['UCZAA'] = dataset['UCZAA'].fillna(dataset['UCZAA'].median())

In [19]:
print(dataset.isna().sum())

Observation          0
Y-Kappa              0
ChipRate             0
BF-CMratio           0
BlowFlow             0
ChipLevel4           1
T-upperExt-2         2
T-lowerExt-2         2
UCZAA                0
WhiteFlow-4          1
AAWhiteSt-4        151
AA-Wood-4            1
ChipMoisture-4       1
SteamFlow-4          1
Lower-HeatT-3        2
Upper-HeatT-3        2
ChipMass-4           1
WeakLiquorF          1
BlackFlow-2          2
WeakWashF            1
SteamHeatF-3         2
T-Top-Chips-4        1
SulphidityL-4      151
dtype: int64


In [20]:
dataset.columns = dataset.columns.str.strip()

In [21]:
print(dataset.columns)

Index(['Observation', 'Y-Kappa', 'ChipRate', 'BF-CMratio', 'BlowFlow',
       'ChipLevel4', 'T-upperExt-2', 'T-lowerExt-2', 'UCZAA', 'WhiteFlow-4',
       'AAWhiteSt-4', 'AA-Wood-4', 'ChipMoisture-4', 'SteamFlow-4',
       'Lower-HeatT-3', 'Upper-HeatT-3', 'ChipMass-4', 'WeakLiquorF',
       'BlackFlow-2', 'WeakWashF', 'SteamHeatF-3', 'T-Top-Chips-4',
       'SulphidityL-4'],
      dtype='object')


In [22]:
print(dataset['AAWhiteSt-4'].mean())
print(dataset['AAWhiteSt-4'].median())


6.140410404624277
6.135


In [23]:
dataset['AAWhiteSt-4'] = dataset['AAWhiteSt-4'].fillna(dataset['AAWhiteSt-4'].mean())

In [24]:
print(dataset['SulphidityL-4'].mean())
print(dataset['SulphidityL-4'].median())

30.41167052023121
30.37


In [25]:
dataset['SulphidityL-4'] = dataset['SulphidityL-4'].fillna(dataset['SulphidityL-4'].mean())

In [26]:
# To check for existence of Missing Values in the given dataset again :-

In [27]:
print(dataset.isnull().sum())

Observation       0
Y-Kappa           0
ChipRate          0
BF-CMratio        0
BlowFlow          0
ChipLevel4        1
T-upperExt-2      2
T-lowerExt-2      2
UCZAA             0
WhiteFlow-4       1
AAWhiteSt-4       0
AA-Wood-4         1
ChipMoisture-4    1
SteamFlow-4       1
Lower-HeatT-3     2
Upper-HeatT-3     2
ChipMass-4        1
WeakLiquorF       1
BlackFlow-2       2
WeakWashF         1
SteamHeatF-3      2
T-Top-Chips-4     1
SulphidityL-4     0
dtype: int64


In [28]:
dataset.dropna(inplace=True)
dataset.reset_index(drop=True,inplace=True)

In [29]:
print(dataset.isna().sum())

Observation       0
Y-Kappa           0
ChipRate          0
BF-CMratio        0
BlowFlow          0
ChipLevel4        0
T-upperExt-2      0
T-lowerExt-2      0
UCZAA             0
WhiteFlow-4       0
AAWhiteSt-4       0
AA-Wood-4         0
ChipMoisture-4    0
SteamFlow-4       0
Lower-HeatT-3     0
Upper-HeatT-3     0
ChipMass-4        0
WeakLiquorF       0
BlackFlow-2       0
WeakWashF         0
SteamHeatF-3      0
T-Top-Chips-4     0
SulphidityL-4     0
dtype: int64


In [30]:
# Therefore, now we have a completely curated dataset that does not contain any missing values

In [31]:
print(dataset.shape)

(318, 23)


In [32]:
# Therefore, the given dataset contains 318 rows and 23 columns

## Data Filtering :-

In [33]:
dataset.head(10)

Observation  Y-Kappa  ChipRate  BF-CMratio  BlowFlow  ChipLevel4  \
0    31-00:00    23.10    16.520     121.717  1177.607     169.805   
1    31-01:00    27.60    16.810      79.022  1328.360     341.327   
2    31-02:00    23.19    16.709      79.562  1329.407     239.161   
3    31-03:00    23.60    16.478      81.011  1334.877     213.527   
4    31-04:00    22.90    15.618      93.244  1334.168     243.131   
5     1-08:00    14.23    15.350      85.518  1171.604     198.538   
6     1-09:00    13.49    13.700      98.186  1243.688     116.275   
7    31-06:00    22.65    14.100      91.887  1307.852     288.989   
8    31-07:00    22.50    14.233      97.249  1346.900     330.325   
9    31-08:00    24.70    13.850      96.208  1334.892     362.511   

   T-upperExt-2  T-lowerExt-2  UCZAA  WhiteFlow-4  ...  SteamFlow-4  \
0       358.282       329.545  1.443      599.253  ...       67.122   
1       351.050       329.067  1.549      537.201  ...       60.012   
2       350.022       329.260  1.600      549.611  ...       61.304   
3       350.938       331.142  1.604      623.362  ...       68.496   
4       351.640       332.709  1.498      638.672  ...       70.022   
5       344.014       325.195  1.436      628.245  ...       65.225   
6       346.208       326.982  1.434      696.766  ...       72.989   
7       352.321       331.162  1.468      625.549  ...       71.298   
8       352.687       328.894  1.480      591.827  ...       68.791   
9       352.372       327.358  1.515      553.172  ...       64.249   

   Lower-HeatT-3  Upper-HeatT-3  ChipMass-4  WeakLiquorF  BlackFlow-2  \
0        329.432        303.099     175.964     1127.197     1319.039   
1        330.823        304.879     163.202      665.975     1297.317   
2        329.140        303.383     164.013      677.534     1327.072   
3        328.875        302.254     181.487      767.853     1324.461   
4        328.352        300.954     183.929      888.448     1343.424   
5        322.103        298.517     165.814      826.243      907.641   
6        322.982        296.080     182.018      784.281      929.527   
7        329.662        301.539     179.886      837.178     1315.111   
8        331.485        303.488     174.804      889.516     1317.912   
9        332.264        305.419     166.120      909.810     1318.725   

   WeakWashF  SteamHeatF-3  T-Top-Chips-4  SulphidityL-4  
0    257.325        54.612        252.077      30.411671  
1    241.182        46.603        251.406      29.110000  
2    237.272        51.795        251.335      30.411671  
3    239.478        54.846        250.312      29.020000  
4    215.372        54.186        249.916      29.010000  
5    595.875        52.807        249.580      30.340000  
6    201.272        58.118        248.741      30.411671  
7    234.047        53.805        249.971      29.220000  
8    226.319        52.546        250.414      30.411671  
9    180.375        48.842        251.121      29.210000  

[10 rows x 23 columns]

In [34]:
print(dataset.columns)

Index(['Observation', 'Y-Kappa', 'ChipRate', 'BF-CMratio', 'BlowFlow',
       'ChipLevel4', 'T-upperExt-2', 'T-lowerExt-2', 'UCZAA', 'WhiteFlow-4',
       'AAWhiteSt-4', 'AA-Wood-4', 'ChipMoisture-4', 'SteamFlow-4',
       'Lower-HeatT-3', 'Upper-HeatT-3', 'ChipMass-4', 'WeakLiquorF',
       'BlackFlow-2', 'WeakWashF', 'SteamHeatF-3', 'T-Top-Chips-4',
       'SulphidityL-4'],
      dtype='object')


### Illustration of Filtering :-

In [35]:
                                # Filtering Column : ChipMass-4 #
dataset1 = dataset[(dataset['ChipMass-4'] >= 175.00)]

In [36]:
dataset1.head()

Observation  Y-Kappa  ChipRate  BF-CMratio  BlowFlow  ChipLevel4  \
0    31-00:00    23.10    16.520     121.717  1177.607     169.805   
3    31-03:00    23.60    16.478      81.011  1334.877     213.527   
4    31-04:00    22.90    15.618      93.244  1334.168     243.131   
6     1-09:00    13.49    13.700      98.186  1243.688     116.275   
7    31-06:00    22.65    14.100      91.887  1307.852     288.989   

   T-upperExt-2  T-lowerExt-2  UCZAA  WhiteFlow-4  ...  SteamFlow-4  \
0       358.282       329.545  1.443      599.253  ...       67.122   
3       350.938       331.142  1.604      623.362  ...       68.496   
4       351.640       332.709  1.498      638.672  ...       70.022   
6       346.208       326.982  1.434      696.766  ...       72.989   
7       352.321       331.162  1.468      625.549  ...       71.298   

   Lower-HeatT-3  Upper-HeatT-3  ChipMass-4  WeakLiquorF  BlackFlow-2  \
0        329.432        303.099     175.964     1127.197     1319.039   
3        328.875        302.254     181.487      767.853     1324.461   
4        328.352        300.954     183.929      888.448     1343.424   
6        322.982        296.080     182.018      784.281      929.527   
7        329.662        301.539     179.886      837.178     1315.111   

   WeakWashF  SteamHeatF-3  T-Top-Chips-4  SulphidityL-4  
0    257.325        54.612        252.077      30.411671  
3    239.478        54.846        250.312      29.020000  
4    215.372        54.186        249.916      29.010000  
6    201.272        58.118        248.741      30.411671  
7    234.047        53.805        249.971      29.220000  

[5 rows x 23 columns]

In [37]:
print(dataset1.shape)

(58, 23)


In [38]:
dataset2 = dataset[(dataset['ChipLevel4'] >= 200.00)]

In [39]:
dataset2.head()

Observation  Y-Kappa  ChipRate  BF-CMratio  BlowFlow  ChipLevel4  \
1    31-01:00    27.60    16.810      79.022  1328.360     341.327   
2    31-02:00    23.19    16.709      79.562  1329.407     239.161   
3    31-03:00    23.60    16.478      81.011  1334.877     213.527   
4    31-04:00    22.90    15.618      93.244  1334.168     243.131   
7    31-06:00    22.65    14.100      91.887  1307.852     288.989   

   T-upperExt-2  T-lowerExt-2  UCZAA  WhiteFlow-4  ...  SteamFlow-4  \
1       351.050       329.067  1.549      537.201  ...       60.012   
2       350.022       329.260  1.600      549.611  ...       61.304   
3       350.938       331.142  1.604      623.362  ...       68.496   
4       351.640       332.709  1.498      638.672  ...       70.022   
7       352.321       331.162  1.468      625.549  ...       71.298   

   Lower-HeatT-3  Upper-HeatT-3  ChipMass-4  WeakLiquorF  BlackFlow-2  \
1        330.823        304.879     163.202      665.975     1297.317   
2        329.140        303.383     164.013      677.534     1327.072   
3        328.875        302.254     181.487      767.853     1324.461   
4        328.352        300.954     183.929      888.448     1343.424   
7        329.662        301.539     179.886      837.178     1315.111   

   WeakWashF  SteamHeatF-3  T-Top-Chips-4  SulphidityL-4  
1    241.182        46.603        251.406      29.110000  
2    237.272        51.795        251.335      30.411671  
3    239.478        54.846        250.312      29.020000  
4    215.372        54.186        249.916      29.010000  
7    234.047        53.805        249.971      29.220000  

[5 rows x 23 columns]

In [40]:
print(dataset2.shape)

(254, 23)


In [41]:
# In each of the filtered dataset we can observe that the ----
# In case of dataset1, the number of rows is 58 rather than 318, indicating the reduction of number of rows due to filtering.
# In case of dataset2, the number of rows observed is 254 rather than 318, indicating the reduction of number of rows due to filtering.

## Summary Statistics Calculation :-

In [42]:
dataset.describe() # Returns Summary Statistics of Numerical features

Y-Kappa    ChipRate  BF-CMratio     BlowFlow  ChipLevel4  \
count  318.000000  318.000000  318.000000   318.000000  318.000000   
mean    20.707358   14.393593   87.454863  1239.210665  261.961994   
std      3.051573    1.458595    7.853198    99.165872   83.203412   
min     12.170000    9.983000   68.645000     0.000000    0.000000   
25%     18.535000   13.425500   82.027750  1194.319250  218.663500   
50%     20.950000   14.361469   87.028500  1273.138500  273.234500   
75%     23.100000   15.517000   92.159250  1288.704500  322.673250   
max     27.600000   16.958000  121.717000  1351.240000  419.014000   

       T-upperExt-2  T-lowerExt-2       UCZAA  WhiteFlow-4  AAWhiteSt-4  ...  \
count    318.000000    318.000000  318.000000   318.000000   318.000000  ...   
mean     356.782387    323.958289    1.490044   593.081824     6.140790  ...   
std        9.177727      7.644769    0.100832    66.406219     0.059921  ...   
min      339.168000    284.633000    1.182000   405.111000     5.890000  ...   
25%      350.170250    321.341250    1.434500   542.007500     6.130000  ...   
50%      356.756500    325.577500    1.498000   593.887000     6.140410  ...   
75%      361.617000    329.131750    1.552750   641.822500     6.142353  ...   
max      399.135000    337.012000    1.747000   731.394000     6.340000  ...   

       SteamFlow-4  Lower-HeatT-3  Upper-HeatT-3  ChipMass-4  WeakLiquorF  \
count   318.000000     318.000000     318.000000  318.000000   318.000000   
mean     66.833855     325.521195     300.486450  162.546167   874.066447   
std       5.532483       4.619526       4.579136   13.914893   122.990005   
min      48.568000     318.051000     293.312000  113.922000   486.938000   
25%      62.713750     321.382000     296.471750  153.735000   789.774250   
50%      67.600500     323.737000     299.008500  164.010500   866.475000   
75%      71.596000     329.845250     304.244750  172.574500   966.470750   
max      76.147000     333.854000     311.146000  189.268000  1226.277000   

       BlackFlow-2   WeakWashF  SteamHeatF-3  T-Top-Chips-4  SulphidityL-4  
count   318.000000  318.000000    318.000000     318.000000     318.000000  
mean   1175.435682  260.743858     49.671969     251.240519      30.416901  
std     150.195016  163.320275      4.553608       1.285237       0.512325  
min     838.948000    0.000000     35.510000     248.359000      29.010000  
25%    1043.210500  132.764750     46.377500     250.312000      30.340000  
50%    1146.550500  263.538000     50.277000     251.357500      30.411671  
75%    1319.038250  398.945250     53.258500     252.334750      30.414168  
max    1395.767000  715.715000     63.332000     254.122000      32.840000  

[8 rows x 22 columns]

In [43]:
# Examination of Summary Statistics reveal the fact that the features namely --- WeakLiquorF and WeakWashF contains outliers, while the other features do not contain outliers.

In [44]:
dataset.describe(include='all') # Returns Summary Statistics of both numerical and categorical features

Observation     Y-Kappa    ChipRate  BF-CMratio     BlowFlow  \
count          318  318.000000  318.000000  318.000000   318.000000   
unique         297         NaN         NaN         NaN          NaN   
top       31-00:00         NaN         NaN         NaN          NaN   
freq             2         NaN         NaN         NaN          NaN   
mean           NaN   20.707358   14.393593   87.454863  1239.210665   
std            NaN    3.051573    1.458595    7.853198    99.165872   
min            NaN   12.170000    9.983000   68.645000     0.000000   
25%            NaN   18.535000   13.425500   82.027750  1194.319250   
50%            NaN   20.950000   14.361469   87.028500  1273.138500   
75%            NaN   23.100000   15.517000   92.159250  1288.704500   
max            NaN   27.600000   16.958000  121.717000  1351.240000   

        ChipLevel4  T-upperExt-2  T-lowerExt-2       UCZAA  WhiteFlow-4  ...  \
count   318.000000    318.000000    318.000000  318.000000   318.000000  ...   
unique         NaN           NaN           NaN         NaN          NaN  ...   
top            NaN           NaN           NaN         NaN          NaN  ...   
freq           NaN           NaN           NaN         NaN          NaN  ...   
mean    261.961994    356.782387    323.958289    1.490044   593.081824  ...   
std      83.203412      9.177727      7.644769    0.100832    66.406219  ...   
min       0.000000    339.168000    284.633000    1.182000   405.111000  ...   
25%     218.663500    350.170250    321.341250    1.434500   542.007500  ...   
50%     273.234500    356.756500    325.577500    1.498000   593.887000  ...   
75%     322.673250    361.617000    329.131750    1.552750   641.822500  ...   
max     419.014000    399.135000    337.012000    1.747000   731.394000  ...   

        SteamFlow-4  Lower-HeatT-3  Upper-HeatT-3  ChipMass-4  WeakLiquorF  \
count    318.000000     318.000000     318.000000  318.000000   318.000000   
unique          NaN            NaN            NaN         NaN          NaN   
top             NaN            NaN            NaN         NaN          NaN   
freq            NaN            NaN            NaN         NaN          NaN   
mean      66.833855     325.521195     300.486450  162.546167   874.066447   
std        5.532483       4.619526       4.579136   13.914893   122.990005   
min       48.568000     318.051000     293.312000  113.922000   486.938000   
25%       62.713750     321.382000     296.471750  153.735000   789.774250   
50%       67.600500     323.737000     299.008500  164.010500   866.475000   
75%       71.596000     329.845250     304.244750  172.574500   966.470750   
max       76.147000     333.854000     311.146000  189.268000  1226.277000   

        BlackFlow-2   WeakWashF  SteamHeatF-3  T-Top-Chips-4  SulphidityL-4  
count    318.000000  318.000000    318.000000     318.000000     318.000000  
unique          NaN         NaN           NaN            NaN            NaN  
top             NaN         NaN           NaN            NaN            NaN  
freq            NaN         NaN           NaN            NaN            NaN  
mean    1175.435682  260.743858     49.671969     251.240519      30.416901  
std      150.195016  163.320275      4.553608       1.285237       0.512325  
min      838.948000    0.000000     35.510000     248.359000      29.010000  
25%     1043.210500  132.764750     46.377500     250.312000      30.340000  
50%     1146.550500  263.538000     50.277000     251.357500      30.411671  
75%     1319.038250  398.945250     53.258500     252.334750      30.414168  
max     1395.767000  715.715000     63.332000     254.122000      32.840000  

[11 rows x 23 columns]

## Summary :-

1) The dataset initially has 324 rows and 23 columns
2) Checking for missing values revealed the fact that missing values are present for several features in case of the given dataset
3) The missing values handling was done by replacing the suitable features with their corresponding computed mean or median
4) In case of others, the features containing missing values were droped altogether and we obtained a dataset that does not contain any missing values present within it. 
5) We finally have a dataset that contains 318 rows and 23 columns
6) Filtering of the dataset was done by considering variables ChipMass-4 and ChipLevel4. Filtering the dataset resulted in a dataset with reduced number of rows in either case.
7) Examination of Summary Statistics reveal the fact that the features namely --- WeakLiquorF and WeakWashF contains outliers, while the other features do not contain outliers.